change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
include-labels:
  - "beta"
  - "breaking-change"
  - "bugfix"
  - "dependencies"
  - "enhancement"
  - "feature"
  - "refactor"
categories:
  - title: "💥 Breaking changes"
    label: "breaking-change"

  - title: "🚧 Beta changes"
    label: "beta"
    collapse-after: 1

  - title: "✨ New features"
    label: "feature"

  - title: "🚀 Performance"
    label: "enhancement"

  - title: "🔨 Refactor"
    label: "refactor"

  - title: "🐛 Bug fixes"
    label: "bugfix"

  - title: "⬆️ Dependency updates"
    label: "dependencies"
    collapse-after: 1

template: |
  $CHANGES

  ***
  If you are using this integration, please consider enabling [Home Assistant usage analytics](https://www.home-assistant.io/integrations/analytics/#usage-analytics).
