#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Set the python path to include our custom_components directory
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug
